/*Luphiwe Sikupela
25-/Apr/2023*/

import Head from "next/head";
import PhotoGrids from "@/components/PhotoGrids";
import MenuBar from "@/components/MenuBar";
import { useRouter } from "next/router";

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <MenuBar />
        <PhotoGrids name={"animation"} />
      </div>
    </>
  );
}
